root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd"
bin = "tmp/app"
full_bin = "tmp/app"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules", "client", "uploads", "data"]

delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true

[misc]
clean_on_exit = true
